### ISSUE TITLE
data type for min_samples parameter for DBSCAN

### ISSUE THREAD

**Issue by JennyLeeStat** [MapperInteractive/MapperInteractive#21]
https://github.com/MapperInteractive/MapperInteractive/blob/8b22b9fd97e0e2e6427a96af2d8f7a89bcf7a8e5/app/views.py#L360

Changing data type of min_samples to float gives me this error: 

"TypeError: min_samples must be an instance of int, not float."

By replacing it with int() instead, I could compute the mapper without problems.

**Comment by zhou325** [comment]
Thank you for pointing that out.
I think the error occurred because the new version of sklearn forces the data type of min_samples to be int. 
I have fixed that in the code.
