### ISSUE TITLE
Provide default `main.js` for km use case

### ISSUE THREAD

**Issue by sauln** [MapperInteractive/MapperInteractive#5]
We should have a default `modules/main.js` so users do not need to supply one when using default Kepler Mapper.

@yaodong, it looks like the user's `main.js` is loaded here:
https://github.com/mappercore/mappercore/blob/133eef004390accadf8aba44ca434b9acad13fd6/static/modules/main.js#L69-L73

Any suggestions on the best way to route this to a default module if `modules/main.js` does not exist?

**Comment by yaodong** [comment]
I'm working on a way to eliminate the requirements for `main.js`.
It should be able to run with a single Python file.

**Comment by yaodong** [comment]
Closing this issue. Please free feel to reopen it if KM integration continues.
